monolog:
    handlers:
        main:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%_error.log"
            action_level: error
            excluded_http_codes: [404, 405]
            max_files: 10
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
