#!/bin/bash
cd ..
mkdir -p var/qa-results
clear
echo "---------------------------------------"
echo "------------ ALEXEY  TESTS ------------"
echo "---------------------------------------"
sleep 1
clear
echo "---------------------------------------"
echo "------- PREPARE DB....."
echo "---------------------------------------"
XDEBUG_MODE=off php bin/console doctrine:database:create --env=test > /dev/null
XDEBUG_MODE=off php bin/console doctrine:migrations:migrate --no-interaction --env=test > /dev/null
XDEBUG_MODE=off php bin/console doctrine:fixtures:load --env=test --no-interaction > /dev/null
clear
echo "---------------------------------------"
echo "------- PHPUNIT:"
echo "---------------------------------------"
XDEBUG_MODE=coverage /var/www/html/vendor/bin/phpunit --verbose --coverage-html var/qa-results/phpunit/test-coverage-report --testdox-html var/qa-results/phpunit/test-result.html --log-junit var/qa-results/phpunit/junit-output.xml
chown -R 1000:1000 var/qa-results/ >/dev/null
echo "----------------- DONE ----------------"
