#!/bin/bash
stoponfail() {
    if [ $? -ne 0 ];
        then exit 1;
    fi
}

clear
cd ..
mkdir -p var/qa-results
rm -rf var/cache
clear
echo "---------------------------------------"
echo "------------ ALEXEY  TESTS ------------"
echo "---------------------------------------"
sleep 1
clear
echo "---------------------------------------"
echo "------- PREPARE DB....."
echo "---------------------------------------"
XDEBUG_MODE=off php bin/console doctrine:database:drop --force --env=test
XDEBUG_MODE=off php bin/console doctrine:database:create --env=test
stoponfail
XDEBUG_MODE=off php bin/console doctrine:migrations:migrate --no-interaction --env=test
stoponfail
XDEBUG_MODE=off php bin/console doctrine:fixtures:load --env=test --no-interaction
stoponfail
echo "---------------------------------------"
echo "------- TWIG CHECKSTYLE:"
echo "---------------------------------------"
XDEBUG_MODE=off /var/www/html/vendor/bin/twigcs templates/ --severity error --display blocking
stoponfail
echo "---------------------------------------"
echo "------- PHPCS (PSR12):"
echo "---------------------------------------"
XDEBUG_MODE=off /var/www/html/vendor/bin/phpcs --standard=PSR12 src
stoponfail
echo "---------------------------------------"
echo "------- WEAK ASSUPTIONS:"
echo "---------------------------------------"
XDEBUG_MODE=off /var/www/html/vendor/bin/phpa src
stoponfail
echo "---------------------------------------"
echo "------- PHPSTAN:"
echo "---------------------------------------"
XDEBUG_MODE=off /var/www/html/vendor/bin/phpstan --level=5 --memory-limit=2048M analyse src
stoponfail
echo "---------------------------------------"
echo "------- PHPUNIT:"
echo "---------------------------------------"
XDEBUG_MODE=coverage APP_ENV=test /var/www/html/vendor/bin/phpunit --verbose --coverage-html var/qa-results/phpunit/test-coverage-report --testdox-html var/qa-results/phpunit/test-result.html --log-junit var/qa-results/phpunit/junit-output.xml
stoponfail
echo "---------------------------------------"
echo "------- PHPMETRICS (-> var/qa-results)"
echo "---------------------------------------"
XDEBUG_MODE=off ./vendor/bin/phpmetrics --report-html=var/qa-results/phpmetrics-report --junit=var/qa-results/phpunit/junit-output.xml . | grep -v -e '^$' | grep -v 'Deprecated'
stoponfail
chown -R 1000:1000 var/qa-results/ >/dev/null
echo "----------------- DONE ----------------"
