#!/bin/bash
cd ..
mkdir -p var/qa-results
clear
echo "---------------------------------------"
echo "------------ ALEXEY  TESTS ------------"
echo "---------------------------------------"
sleep 1
clear
echo "---------------------------------------"
echo "------- PHPUNIT:"
echo "---------------------------------------"
XDEBUG_MODE=coverage /var/www/html/vendor/bin/phpunit --verbose --coverage-html var/qa-results/phpunit/test-coverage-report --testdox-html var/qa-results/phpunit/test-result.html --log-junit var/qa-results/phpunit/junit-output.xml
chown -R 1000:1000 var/qa-results/ >/dev/null
echo "----------------- DONE ----------------"
