#!/bin/bash
clear
cd ..
XDEBUG_MODE=off php bin/console cache:clear
clear
XDEBUG_MODE=off php bin/console translation:update --format=yaml --force en
XDEBUG_MODE=off php bin/console translation:update --format=yaml --force pl
