#!/bin/bash
clear
cd ..
XDEBUG_MODE=off php bin/console cache:clear
clear
XDEBUG_MODE=off php bin/console debug:translation en --only-missing
XDEBUG_MODE=off php bin/console debug:translation pl --only-missing
