#!/bin/bash
clear
echo "Creating backup..."
gzip --best backups/backup_all_databases_current.sql
mv backups/backup_all_databases_current.sql.gz backups/backup_before_$(date +%Y_%m_%d_%H_%M_%S).sql.gz > /dev/null
docker exec alexey-mysql sh -c 'exec mysqldump --all-databases -uroot -p"$MYSQL_ROOT_PASSWORD"' > backups/backup_all_databases_current.sql
cd backups
if [ $(ls | wc -l) -gt 10 ]; then
    rm "$(ls -t | tail -1)"
fi
if [ $(ls | wc -l) -gt 10 ]; then
    rm "$(ls -t | tail -1)"
fi
echo "Backup finished"
