#!/bin/bash
echo "Stopping containers..."
docker stop alexey-php
docker stop alexey-phpmyadmin
docker stop alexey-nginx
docker stop alexey-mysql
echo "Stashing local changes..."
git stash -u
echo "Updating codebase..."
git pull
echo "Reapplying stash..."
git stash pop
echo "Starting containers..."
./alexey_install_detach
