# https://github.com/compose-spec/compose-spec/blob/master/spec.md
services:
    database:
        env_file: 
            - .env
        image: mysql:8.0
        container_name: "alexey-mysql"
        restart: always
        expose:
            - 3306
        networks:
            - network
        volumes:
            - database_volume:/var/lib/mysql
            - ./entrails/mysql_conf:/etc/mysql/conf.d
        logging:
          driver: json-file
          options:
              max-size: "5m"
              max-file: "2"
    phpmyadmin:
        env_file:
            - .env
        image: phpmyadmin/phpmyadmin
        container_name: "alexey-phpmyadmin"
        expose:
            - 80
        networks:
            - network
        restart: always
        depends_on:
            - database
        logging:
          driver: json-file
          options:
              max-size: "5m"
              max-file: "2"
    php:
        environment:
            - DEVELOPMENT=1
        build:
            context: ./entrails/php-fpm
            dockerfile: Dockerfile
        container_name: "alexey-php"
        expose:
            - 9000
        networks:
            - network
            - wake_lan
        depends_on:
            - database
        volumes:
            - ./../application:/var/www/html
        restart: always
        logging:
          driver: json-file
          options:
              max-size: "5m"
              max-file: "2"
        extra_hosts:
            - "host.docker.internal:host-gateway"
    nginx:
        env_file:
            - .env
        image: nginx
        container_name: "alexey-nginx"
        ports:
            - 80:80
            - 443:443
        networks:
            - network
        restart: always
        depends_on:
            - php
            - database
        volumes:
            - ./../application:/var/www/html
            - ./entrails/nginx/vhosts:/etc/nginx/vhost.d
            - ./entrails/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./entrails/nginx/ssl:/etc/nginx/ssl
        logging:
          driver: json-file
          options:
              max-size: "5m"
              max-file: "2"
volumes:
    database_volume: {}

networks:
    network:
    wake_lan:
        driver: macvlan
        driver_opts:
            parent: enp3s0  #set your host network card here, i.e. eth0
        ipam:
            driver: default
            config:
                - subnet: 192.168.1.0/24  #set your network addressation here
