#!/bin/bash
cd ../backups
echo "Creating backup..."
gzip --best backup_all_databases_current.sql
mv backup_all_databases_current.sql.gz backup_before_$(date +%Y_%m_%d___%H_%M).sql.gz > /dev/null
docker exec alexey-mysql sh -c 'exec mysqldump --all-databases -uroot -p"$MYSQL_ROOT_PASSWORD"' > backup_all_databases_current.sql
if [ $(ls | wc -l) -gt 30 ]; then
    rm "$(ls -t | tail -1)"
fi
if [ $(ls | wc -l) -gt 30 ]; then
    rm "$(ls -t | tail -1)"
fi
echo "Backup finished"
