#!/bin/bash
cd ../docker
echo "-----------------------------------------------------"
echo "------ [ ALEXEY WILL BE LIVE IN FEW MOMENTS! ] ------"
echo "-----------------------------------------------------"
echo "---------------- [ HAVE  PATIENCE! ] ----------------"
echo "-----------------------------------------------------"
sleep 3
docker-compose build --pull --parallel --no-cache --force-rm
docker-compose up --detach
echo "you may need to run ./fix_permissions script after cache warmup (minute or two), will address this issue in next fix"
# ./../scripts/fix_permissions #TODO automate permissions fix
