#!/bin/bash
cd ../docker
echo "-----------------------------------------------------"
echo "------ [ ALEXEY WILL BE LIVE IN FEW MOMENTS! ] ------"
echo "-----------------------------------------------------"
echo "---------------- [ HAVE  PATIENCE! ] ----------------"
echo "-----------------------------------------------------"
sleep 3
docker compose build --pull --parallel --no-cache --force-rm
docker compose up
