#!/bin/bash
cd ../docker
rm -f entrails/nginx/ssl/alexey.key
rm -f entrails/nginx/ssl/alexey.crt
openssl req -x509 -newkey rsa:4096 -keyout entrails/nginx/ssl/alexey.key -out entrails/nginx/ssl/alexey.crt -days 365 -nodes
