#!/bin/bash
cd ../docker
clear
echo "setup ---> Common Name (e.g. server FQDN or YOUR name) <--- to your ip address"
rm -f entrails/nginx/ssl/alexey.key
rm -f entrails/nginx/ssl/alexey.crt
openssl req -x509 -newkey rsa:4096 -keyout entrails/nginx/ssl/alexey.key -out entrails/nginx/ssl/alexey.crt -days 3650 -nodes
