#!/bin/bash
cd ../application
mkdir -p var/qa-results
rm -rf var/qa-results/*
clear
echo "updating QA toolset..."
docker pull jakzal/phpqa
clear
shopt -s expand_aliases
alias phpqa='docker run --init -it --rm -v "$(pwd):/project" -v "/tmp/tmp-phpqa:/tmp" -w /project jakzal/phpqa'
echo "---------------------------------------"
echo "-------------PHPSTAN:"
echo "---------------------------------------"
# Adjust --level parameter from 1 to 8, 8 being the most strict
phpqa phpstan --level=1 --memory-limit=2048M analyse src
echo "---------------------------------------"
echo "-------------COMPOSER REQUIRE CHECKER:"
echo "---------------------------------------"
# For PHP 7.3 use composer-require-checker-v2
phpqa composer-require-checker
echo "---------------------------------------"
echo "-------------COMPOSER UNUSED:"
echo "---------------------------------------"
phpqa composer-unused
echo "---------------------------------------"
echo "-------------DEPHPEND:"
echo "---------------------------------------"
phpqa dephpend dsm src > var/qa-results/dephpend-dependencies.html
phpqa dephpend metrics src
echo "---------------------------------------"
echo "-------------PHPCS (PSR12):"
echo "---------------------------------------"
phpqa phpcs --standard=PSR12 src
echo "---------------------------------------"
echo "-------------SECURITY CHECKER:"
echo "---------------------------------------"
phpqa local-php-security-checker
echo "---------------------------------------"
echo "-------------WEAK ASSUPTIONS:"
echo "---------------------------------------"
phpqa phpa src
echo "---------------------------------------"
echo "-------------PHPCA:"
echo "---------------------------------------"
# PhpCodeAnalyzer finds usage of different non-built-in extensions in your php code.
# This tool helps you understand how transportable your code between php installations is.
phpqa phpca src
echo "---------------------------------------"
echo "-------------PHPCPD:"
echo "---------------------------------------"
# Checking repeated code
phpqa phpcpd --fuzzy src/
echo "---------------------------------------"
echo "-------------PHPDD:"
echo "---------------------------------------"
# Seeks deprecations
# Available target versions: 5.3, 5.4, 5.5, 5.6, 7.0, 7.1, 7.2, 7.3, 7.4
phpqa phpdd --max-size=100M --after=7.4 src/
echo "---------------------------------------"
echo "-------------PHPLOC:"
echo "---------------------------------------"
phpqa phploc src/
echo "---------------------------------------"
echo "-------------TWIG CHECKSTYLE:"
echo "---------------------------------------"
phpqa twigcs templates/ --severity error --display blocking
# Fix permissions
phpqa chown -R 1000:1000 var/qa-results/
echo "---------------FINISHED----------------"
