#!/bin/bash
clear
read -p "Are you sure you want to uninstall alexey? <y/N> " prompt
if [[ $prompt == "y" || $prompt == "Y" || $prompt == "yes" || $prompt == "Yes" ]]
then
    clear
    echo "Stopping containers..."
    docker stop alexey-php
    docker stop alexey-phpmyadmin
    docker stop alexey-nginx
    docker stop alexey-mysql
    docker stop alexey-valkey
    docker stop alexey-searxng
    clear
    echo "Removing containers..."
    docker rm alexey-php
    docker rm alexey-phpmyadmin
    docker rm alexey-nginx
    docker rm alexey-mysql
    docker rm alexey-valkey
    docker rm alexey-searxng
    clear
    echo "Removing images..."
    docker rmi alexey-php
    docker rmi alexey-nginx
    #docker image prune
    clear
    echo "Removing data volumes..."
    docker volume rm alexey_database_volume
    docker volume rm alexey_valkey_data
    #docker volume prune
    echo "Removing networks..."
    docker network rm alexey_network
    docker network rm alexey_wake_lan
    clear
    echo "------------------------------------"
    echo "------ [ ALEXEY UNINSTALLED ] ------"
    echo "------------------------------------"
else
    exit 0
fi
