#!/bin/bash
clear
echo "Stopping containers..."
docker stop alexey-php
docker stop alexey-phpmyadmin
docker stop alexey-nginx
./database_backup
docker stop alexey-mysql
echo "Stashing local changes..."
git stash -u
echo "Updating codebase..."
git pull
echo "Reapplying stash..."
git stash pop
git stash clear
echo "Starting containers..."
./install_detach
