framework:
    messenger:
        transports:
            async_queue:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                options:
                    queue_name: queue_async
                retry_strategy: 
                    max_retries: 0
                    delay: 10

        routing:
            'App\Message\AsyncJob': async_queue
            'Symfony\Component\Mailer\Messenger\SendEmailMessage': async_queue
