# https://github.com/compose-spec/compose-spec/blob/master/spec.md
version: '3.5'
services:
  node:
    build:
      context: .
      args:
        - NODE_ENV=development
    environment:
      - NODE_ENV=development
    tty: true
    working_dir: /home/node/app
    volumes:
        - './../application:/home/node/app'
    restart: always
    network_mode: host
    container_name: 'alexey-companion'
    logging:
      driver: json-file
      options:
          max-size: '5m'
          max-file: '2'
