#!/bin/bash
docker exec -it -w /home/node/app alexey-companion yarn install
docker exec -d -w /home/node/app alexey-companion ./serve
echo "----------------------------------------------"
echo "----------------------------------------------"
echo "---- [ BUNDLER:  http://localhost:19002 ] ----"
echo "----------------------------------------------"
echo "------ [ WEB:  http://localhost:19006 ] ------"
echo "----------------------------------------------"
echo "----------------------------------------------"
